name: classical-cryptography
version: 0.1.0.0
synopsis: Classical Cryptography
description: See report.pdf
maintainer: Sütő Zsolt András <andras.suto2@student.uva.nl>
category: Cryptography

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - report

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - report
      - QuickCheck
      - hspec
